"""initial

Revision ID: 2f2824be38bc
Revises:
Create Date: 2025-12-23 12:43:53.080607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2824be38bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dish_active'), 'dish', ['active'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('tg_id', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name='check_email_or_phone_not_null'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('tg_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_active'), 'user', ['active'], unique=False)
    op.create_table('image_media',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_image_media_active'), 'image_media', ['active'], unique=False)
    op.create_table('cafe',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['image_media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', name='uq_cafe_name_address'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('photo_id')
    )
    op.create_index('idx_cafe_name', 'cafe', ['name'], unique=False)
    op.create_index(op.f('ix_cafe_active'), 'cafe', ['active'], unique=False)
    op.create_table('booking',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя, который создал бронь'),
    sa.Column('cafe_id', sa.UUID(), nullable=False, comment='ID кафе, в котором создана бронь'),
    sa.Column('guest_number', sa.Integer(), nullable=False, comment='Количество гостей'),
    sa.Column('booking_date', sa.Date(), nullable=False, comment='Дата брони'),
    sa.Column('note', sa.String(length=255), nullable=False, comment='Примечание к брони'),
    sa.Column('status', sa.Enum('BOOKING', 'CANCELED', 'ACTIVE', 'COMPLETED', name='booking_status'), nullable=False, comment='Статус брони'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_active'), 'booking', ['active'], unique=False)
    op.create_index('ix_booking_cafe_date', 'booking', ['cafe_id', 'booking_date'], unique=False)
    op.create_index('ix_booking_user_id', 'booking', ['user_id'], unique=False)
    op.create_table('cafes_managers',
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('cafe_id', 'user_id')
    )
    op.create_table('dishes_cafes',
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'cafe_id')
    )
    op.create_table('slot',
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='slot_start_before_end'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_active'), 'slot', ['active'], unique=False)
    op.create_table('table',
    sa.Column('cafe_id', sa.UUID(), nullable=False),
    sa.Column('count_place', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('count_place > 0 and count_place <= 20', name='table_places_range'),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_active'), 'table', ['active'], unique=False)
    op.create_table('booking_table_slot',
    sa.Column('booking_id', sa.UUID(), nullable=False, comment='Ссылка на бронь'),
    sa.Column('table_id', sa.UUID(), nullable=False, comment='Ссылка на забронированный стол'),
    sa.Column('slot_id', sa.UUID(), nullable=False, comment='Ссылка на временной слот'),
    sa.Column('booking_date', sa.Date(), nullable=False, comment='Дата брони (копия из Booking, для уникальности стол+слот+дата)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_table_slot_active'), 'booking_table_slot', ['active'], unique=False)
    op.create_index('ix_booking_table_slot_slot_date', 'booking_table_slot', ['slot_id', 'booking_date'], unique=False)
    op.create_index('ix_booking_table_slot_table_date', 'booking_table_slot', ['table_id', 'booking_date'], unique=False)
    op.create_index('uq_table_slot_booking_date_when_active', 'booking_table_slot', ['table_id', 'slot_id', 'booking_date'], unique=True, postgresql_where=sa.text('active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_table_slot_booking_date_when_active', table_name='booking_table_slot', postgresql_where=sa.text('active = true'))
    op.drop_index('ix_booking_table_slot_table_date', table_name='booking_table_slot')
    op.drop_index('ix_booking_table_slot_slot_date', table_name='booking_table_slot')
    op.drop_index(op.f('ix_booking_table_slot_active'), table_name='booking_table_slot')
    op.drop_table('booking_table_slot')
    op.drop_index(op.f('ix_table_active'), table_name='table')
    op.drop_table('table')
    op.drop_index(op.f('ix_slot_active'), table_name='slot')
    op.drop_table('slot')
    op.drop_table('dishes_cafes')
    op.drop_table('cafes_managers')
    op.drop_index('ix_booking_user_id', table_name='booking')
    op.drop_index('ix_booking_cafe_date', table_name='booking')
    op.drop_index(op.f('ix_booking_active'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_cafe_active'), table_name='cafe')
    op.drop_index('idx_cafe_name', table_name='cafe')
    op.drop_table('cafe')
    op.drop_index(op.f('ix_image_media_active'), table_name='image_media')
    op.drop_table('image_media')
    op.drop_index(op.f('ix_user_active'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_dish_active'), table_name='dish')
    op.drop_table('dish')
    # ### end Alembic commands ###
