"""добавление связи кафе и блюд

Revision ID: 83f91691cb31
Revises: 25a816cf4e42
Create Date: 2025-12-20 09:47:55.914844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83f91691cb31'
down_revision: Union[str, Sequence[str], None] = '25a816cf4e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('booking', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('booking_table_slot', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('booking_table_slot', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('cafe', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('cafe', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(op.f('cafe_address_key'), 'cafe', type_='unique')
    op.drop_constraint(op.f('cafe_name_key'), 'cafe', type_='unique')
    op.create_index('idx_cafe_name', 'cafe', ['name'], unique=False)
    op.create_unique_constraint('uq_cafe_name_address', 'cafe', ['name', 'address'])
    op.drop_constraint(op.f('cafes_managers_cafe_id_fkey'), 'cafes_managers', type_='foreignkey')
    op.drop_constraint(op.f('cafes_managers_user_id_fkey'), 'cafes_managers', type_='foreignkey')
    op.create_foreign_key(None, 'cafes_managers', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cafes_managers', 'cafe', ['cafe_id'], ['id'])
    op.alter_column('dish', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('dish', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(op.f('dishes_cafes_cafe_id_fkey'), 'dishes_cafes', type_='foreignkey')
    op.drop_constraint(op.f('dishes_cafes_dish_id_fkey'), 'dishes_cafes', type_='foreignkey')
    op.create_foreign_key(None, 'dishes_cafes', 'dish', ['dish_id'], ['id'])
    op.create_foreign_key(None, 'dishes_cafes', 'cafe', ['cafe_id'], ['id'])
    op.add_column('slot', sa.Column('description', sa.String(length=500), nullable=True))
    op.alter_column('slot', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('slot', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(op.f('slot_cafe_id_key'), 'slot', type_='unique')
    op.drop_constraint(op.f('slot_cafe_id_fkey'), 'slot', type_='foreignkey')
    op.create_foreign_key(None, 'slot', 'cafe', ['cafe_id'], ['id'])
    op.alter_column('table', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('table', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(op.f('table_cafe_id_fkey'), 'table', type_='foreignkey')
    op.create_foreign_key(None, 'table', 'cafe', ['cafe_id'], ['id'])
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(None, 'table', type_='foreignkey')
    op.create_foreign_key(op.f('table_cafe_id_fkey'), 'table', 'cafe', ['cafe_id'], ['id'], ondelete='CASCADE')
    op.alter_column('table', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('table', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.create_foreign_key(op.f('slot_cafe_id_fkey'), 'slot', 'cafe', ['cafe_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('slot_cafe_id_key'), 'slot', ['cafe_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('slot', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('slot', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_column('slot', 'description')
    op.drop_constraint(None, 'dishes_cafes', type_='foreignkey')
    op.drop_constraint(None, 'dishes_cafes', type_='foreignkey')
    op.create_foreign_key(op.f('dishes_cafes_dish_id_fkey'), 'dishes_cafes', 'dish', ['dish_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('dishes_cafes_cafe_id_fkey'), 'dishes_cafes', 'cafe', ['cafe_id'], ['id'], ondelete='CASCADE')
    op.alter_column('dish', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('dish', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(None, 'cafes_managers', type_='foreignkey')
    op.drop_constraint(None, 'cafes_managers', type_='foreignkey')
    op.create_foreign_key(op.f('cafes_managers_user_id_fkey'), 'cafes_managers', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('cafes_managers_cafe_id_fkey'), 'cafes_managers', 'cafe', ['cafe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_cafe_name_address', 'cafe', type_='unique')
    op.drop_index('idx_cafe_name', table_name='cafe')
    op.create_unique_constraint(op.f('cafe_name_key'), 'cafe', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('cafe_address_key'), 'cafe', ['address'], postgresql_nulls_not_distinct=False)
    op.alter_column('cafe', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('cafe', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('booking_table_slot', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('booking_table_slot', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('booking', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('booking', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    # ### end Alembic commands ###
